// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/family.proto

package family

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FamilyService_Join_FullMethodName        = "/family.FamilyService/Join"
	FamilyService_GetFamily_FullMethodName   = "/family.FamilyService/GetFamily"
	FamilyService_ReceiveChat_FullMethodName = "/family.FamilyService/ReceiveChat"
)

// FamilyServiceClient is the client API for FamilyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Aile servisi
type FamilyServiceClient interface {
	Join(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*FamilyView, error)
	GetFamily(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FamilyView, error)
	ReceiveChat(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Empty, error)
}

type familyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFamilyServiceClient(cc grpc.ClientConnInterface) FamilyServiceClient {
	return &familyServiceClient{cc}
}

func (c *familyServiceClient) Join(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*FamilyView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FamilyView)
	err := c.cc.Invoke(ctx, FamilyService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) GetFamily(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FamilyView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FamilyView)
	err := c.cc.Invoke(ctx, FamilyService_GetFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) ReceiveChat(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FamilyService_ReceiveChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FamilyServiceServer is the server API for FamilyService service.
// All implementations must embed UnimplementedFamilyServiceServer
// for forward compatibility.
//
// Aile servisi
type FamilyServiceServer interface {
	Join(context.Context, *NodeInfo) (*FamilyView, error)
	GetFamily(context.Context, *Empty) (*FamilyView, error)
	ReceiveChat(context.Context, *ChatMessage) (*Empty, error)
	mustEmbedUnimplementedFamilyServiceServer()
}

// UnimplementedFamilyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFamilyServiceServer struct{}

func (UnimplementedFamilyServiceServer) Join(context.Context, *NodeInfo) (*FamilyView, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedFamilyServiceServer) GetFamily(context.Context, *Empty) (*FamilyView, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFamily not implemented")
}
func (UnimplementedFamilyServiceServer) ReceiveChat(context.Context, *ChatMessage) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveChat not implemented")
}
func (UnimplementedFamilyServiceServer) mustEmbedUnimplementedFamilyServiceServer() {}
func (UnimplementedFamilyServiceServer) testEmbeddedByValue()                       {}

// UnsafeFamilyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FamilyServiceServer will
// result in compilation errors.
type UnsafeFamilyServiceServer interface {
	mustEmbedUnimplementedFamilyServiceServer()
}

func RegisterFamilyServiceServer(s grpc.ServiceRegistrar, srv FamilyServiceServer) {
	// If the following call panics, it indicates UnimplementedFamilyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FamilyService_ServiceDesc, srv)
}

func _FamilyService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).Join(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_GetFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GetFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_GetFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GetFamily(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_ReceiveChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).ReceiveChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_ReceiveChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).ReceiveChat(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// FamilyService_ServiceDesc is the grpc.ServiceDesc for FamilyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FamilyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "family.FamilyService",
	HandlerType: (*FamilyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _FamilyService_Join_Handler,
		},
		{
			MethodName: "GetFamily",
			Handler:    _FamilyService_GetFamily_Handler,
		},
		{
			MethodName: "ReceiveChat",
			Handler:    _FamilyService_ReceiveChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/family.proto",
}
