// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: family.proto

package family

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type FamilyView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*NodeInfo            `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyView) Reset() {
	*x = FamilyView{}
	mi := &file_family_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyView) ProtoMessage() {}

func (x *FamilyView) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyView.ProtoReflect.Descriptor instead.
func (*FamilyView) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{1}
}

func (x *FamilyView) GetMembers() []*NodeInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_family_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{2}
}

type StoredMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredMessage) Reset() {
	*x = StoredMessage{}
	mi := &file_family_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessage) ProtoMessage() {}

func (x *StoredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessage.ProtoReflect.Descriptor instead.
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{3}
}

func (x *StoredMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoredMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StoreResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResult) Reset() {
	*x = StoreResult{}
	mi := &file_family_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResult) ProtoMessage() {}

func (x *StoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResult.ProtoReflect.Descriptor instead.
func (*StoreResult) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{4}
}

func (x *StoreResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MessageId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageId) Reset() {
	*x = MessageId{}
	mi := &file_family_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageId) ProtoMessage() {}

func (x *MessageId) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageId.ProtoReflect.Descriptor instead.
func (*MessageId) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{5}
}

func (x *MessageId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_family_proto protoreflect.FileDescriptor

const file_family_proto_rawDesc = "" +
	"\n" +
	"\ffamily.proto\x12\x06family\"2\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"8\n" +
	"\n" +
	"FamilyView\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.family.NodeInfoR\amembers\"\a\n" +
	"\x05Empty\"3\n" +
	"\rStoredMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"=\n" +
	"\vStoreResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1b\n" +
	"\tMessageId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xd8\x01\n" +
	"\rFamilyService\x12,\n" +
	"\x04Join\x12\x10.family.NodeInfo\x1a\x12.family.FamilyView\x12.\n" +
	"\tGetFamily\x12\r.family.Empty\x1a\x12.family.FamilyView\x123\n" +
	"\x05Store\x12\x15.family.StoredMessage\x1a\x13.family.StoreResult\x124\n" +
	"\bRetrieve\x12\x11.family.MessageId\x1a\x15.family.StoredMessageB\x15Z\x13proto/family;familyb\x06proto3"

var (
	file_family_proto_rawDescOnce sync.Once
	file_family_proto_rawDescData []byte
)

func file_family_proto_rawDescGZIP() []byte {
	file_family_proto_rawDescOnce.Do(func() {
		file_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_family_proto_rawDesc), len(file_family_proto_rawDesc)))
	})
	return file_family_proto_rawDescData
}

var file_family_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_family_proto_goTypes = []any{
	(*NodeInfo)(nil),      // 0: family.NodeInfo
	(*FamilyView)(nil),    // 1: family.FamilyView
	(*Empty)(nil),         // 2: family.Empty
	(*StoredMessage)(nil), // 3: family.StoredMessage
	(*StoreResult)(nil),   // 4: family.StoreResult
	(*MessageId)(nil),     // 5: family.MessageId
}
var file_family_proto_depIdxs = []int32{
	0, // 0: family.FamilyView.members:type_name -> family.NodeInfo
	0, // 1: family.FamilyService.Join:input_type -> family.NodeInfo
	2, // 2: family.FamilyService.GetFamily:input_type -> family.Empty
	3, // 3: family.FamilyService.Store:input_type -> family.StoredMessage
	5, // 4: family.FamilyService.Retrieve:input_type -> family.MessageId
	1, // 5: family.FamilyService.Join:output_type -> family.FamilyView
	1, // 6: family.FamilyService.GetFamily:output_type -> family.FamilyView
	4, // 7: family.FamilyService.Store:output_type -> family.StoreResult
	3, // 8: family.FamilyService.Retrieve:output_type -> family.StoredMessage
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_family_proto_init() }
func file_family_proto_init() {
	if File_family_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_family_proto_rawDesc), len(file_family_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_family_proto_goTypes,
		DependencyIndexes: file_family_proto_depIdxs,
		MessageInfos:      file_family_proto_msgTypes,
	}.Build()
	File_family_proto = out.File
	file_family_proto_goTypes = nil
	file_family_proto_depIdxs = nil
}
