// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/family.proto

package family

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_family_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type FamilyView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*NodeInfo            `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyView) Reset() {
	*x = FamilyView{}
	mi := &file_proto_family_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyView) ProtoMessage() {}

func (x *FamilyView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyView.ProtoReflect.Descriptor instead.
func (*FamilyView) Descriptor() ([]byte, []int) {
	return file_proto_family_proto_rawDescGZIP(), []int{1}
}

func (x *FamilyView) GetMembers() []*NodeInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_family_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_family_proto_rawDescGZIP(), []int{2}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	FromHost      string                 `protobuf:"bytes,2,opt,name=from_host,json=fromHost,proto3" json:"from_host,omitempty"`
	FromPort      int32                  `protobuf:"varint,3,opt,name=from_port,json=fromPort,proto3" json:"from_port,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_family_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_family_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_family_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetFromHost() string {
	if x != nil {
		return x.FromHost
	}
	return ""
}

func (x *ChatMessage) GetFromPort() int32 {
	if x != nil {
		return x.FromPort
	}
	return 0
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_family_proto protoreflect.FileDescriptor

const file_proto_family_proto_rawDesc = "" +
	"\n" +
	"\x12proto/family.proto\x12\x06family\"2\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"8\n" +
	"\n" +
	"FamilyView\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.family.NodeInfoR\amembers\"\a\n" +
	"\x05Empty\"y\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tfrom_host\x18\x02 \x01(\tR\bfromHost\x12\x1b\n" +
	"\tfrom_port\x18\x03 \x01(\x05R\bfromPort\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\xa0\x01\n" +
	"\rFamilyService\x12,\n" +
	"\x04Join\x12\x10.family.NodeInfo\x1a\x12.family.FamilyView\x12.\n" +
	"\tGetFamily\x12\r.family.Empty\x1a\x12.family.FamilyView\x121\n" +
	"\vReceiveChat\x12\x13.family.ChatMessage\x1a\r.family.EmptyB\x15Z\x13proto/family;familyb\x06proto3"

var (
	file_proto_family_proto_rawDescOnce sync.Once
	file_proto_family_proto_rawDescData []byte
)

func file_proto_family_proto_rawDescGZIP() []byte {
	file_proto_family_proto_rawDescOnce.Do(func() {
		file_proto_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_family_proto_rawDesc), len(file_proto_family_proto_rawDesc)))
	})
	return file_proto_family_proto_rawDescData
}

var file_proto_family_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_family_proto_goTypes = []any{
	(*NodeInfo)(nil),    // 0: family.NodeInfo
	(*FamilyView)(nil),  // 1: family.FamilyView
	(*Empty)(nil),       // 2: family.Empty
	(*ChatMessage)(nil), // 3: family.ChatMessage
}
var file_proto_family_proto_depIdxs = []int32{
	0, // 0: family.FamilyView.members:type_name -> family.NodeInfo
	0, // 1: family.FamilyService.Join:input_type -> family.NodeInfo
	2, // 2: family.FamilyService.GetFamily:input_type -> family.Empty
	3, // 3: family.FamilyService.ReceiveChat:input_type -> family.ChatMessage
	1, // 4: family.FamilyService.Join:output_type -> family.FamilyView
	1, // 5: family.FamilyService.GetFamily:output_type -> family.FamilyView
	2, // 6: family.FamilyService.ReceiveChat:output_type -> family.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_family_proto_init() }
func file_proto_family_proto_init() {
	if File_proto_family_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_family_proto_rawDesc), len(file_proto_family_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_family_proto_goTypes,
		DependencyIndexes: file_proto_family_proto_depIdxs,
		MessageInfos:      file_proto_family_proto_msgTypes,
	}.Build()
	File_proto_family_proto = out.File
	file_proto_family_proto_goTypes = nil
	file_proto_family_proto_depIdxs = nil
}
